config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users

  resources :tasks do
    member do
      get :done
      get :reset_task
    end
  end

  resources :current_day_lists

end

app/models/current_day_list.rb
class CurrentDayList < ActiveRecord::Base
  has_many :daily_tasks
  validates :title, uniqueness: true
end

app/models/daily_task.rb
class DailyTask < ActiveRecord::Base
  belongs_to :current_day_list
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :title, :description, :date_schedule
  validates_uniqueness_of :title
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/current_day_lists_controller.rb
class CurrentDayListsController < ApplicationController
  before_action :set_current_day_list, only: [:show]
  before_action :authenticate_user!

  def index
    @current_day_lists = CurrentDayList.all
  end

  def show
    @daily_tasks = @current_day_list.daily_tasks.all
  end

  private

    def set_current_day_list
      @current_day_list = CurrentDayList.find(params[:id])
    end

end

app/controllers/daily_tasks_controller.rb
class DailyTasksController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include CurrentDayListHelper
  before_action :authenticate_user!
  def home
    #current date for title of homepage
    @current_date = Date.today.strftime("%A %d %B, %Y")
    # call method to get all current tasks for the current day
    current_tasks = populate_current_tasks
    #create a new CurretnDayList if one isn't already created
    @current_day_list = CurrentDayList.find_or_create_by(title: @current_date)
    #instantiate daily tasks array
    @daily_tasks = []
    #populate_currentdaylist(current_tasks)
    @complete_task_count = 0
    @incomplete_task_count = 0
    #builds incomplete and incomplete values in current_day_list_helper
    count_complete_and_incomplete_tasks(current_tasks)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to @task
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render edit_path(@task)
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def done
    done_task = params[:done_task].to_i
    completed_task = DailyTask.find(done_task)
    completed_task.update(complete: true)
    redirect_to root_path
  end

  def reset_task
    done_task = params[:reset_task].to_i
    completed_task = DailyTask.find(done_task)
    completed_task.update(complete: false)
    redirect_to root_path
  end

  private

    def task_params
      params.require(:task).permit(:title, :description, :date_schedule, :repeats, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
    end

    def set_task
      @task = Task.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_day_list_helper.rb
module CurrentDayListHelper

  def populate_current_tasks
    #converts day name to a downcased string
    current_day = Date.today.strftime("%A").to_s.downcase
    current_tasks = []
    #goes through every task and matches task day value
    #to current_day string. Adds to array if there's a match
    current_user.tasks.all.each do |task|
      if task.repeats == true
        if current_day == "monday" && task.monday == true
          current_tasks.push(task)
        elsif current_day == "tuesday" && task.tuesday == true
          current_tasks.push(task)
        elsif current_day == "wednesday" && task.wednesday == true
          current_tasks.push(task)
        elsif current_day == "thursday" && task.thursday == true
          current_tasks.push(task)
        elsif current_day == "friday" && task.friday == true
          current_tasks.push(task)
        elsif current_day == "saturday" && task.saturday == true
          current_tasks.push(task)
        elsif current_day == "sunday" && task.sunday == true
          current_tasks.push(task)
        end
        #matches date on task to current date and adds to array if matched
      elsif task.date_schedule.strftime("%A %d %B, %Y") == Date.today.strftime("%A %d %B, %Y")
        current_tasks.push(task)
      end
    end
    return current_tasks
  end

  def count_complete_and_incomplete_tasks(current_tasks)
    current_tasks.each do |cst|
      @cdl = @current_day_list.daily_tasks.find_or_create_by(title: cst.title, description: cst.description, complete: [true, false])
      @daily_tasks.push(@cdl)
      if @cdl.complete == true
        @complete_task_count += 1
      elsif @cdl.complete == false
        @incomplete_task_count += 1
      end
      if @incomplete_task_count == 0
        @user = current_user.email
        UserMailer.jobs_done(@user).deliver_now
      end
    end
  end

end

app/helpers/daily_tasks_helper.rb
module DailyTasksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/current_day_lists/index.html.erb
<div class="bg-info text-center top-info">
  <p>
    <h4>Click on a date to see a list of tasks completed on that day.</h4><br>
    If there is no entry for the current day, navigate to <%= link_to "the homepage", root_path %> to create one based on the current day's tasks.
  </p>
</div>
<table class="table">
  <tr>
    <th>Date</th>
  </tr>
  <% @current_day_lists.each do |cdl| %>
    <tr>
      <td><%= link_to cdl.title, current_day_list_path(cdl) %></td>
    </tr>
  <% end %>
</table>

app/views/current_day_lists/show.html.erb
<h2><%= @current_day_list.title %></h2>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Complete?</th>
    <th>Update Time</td>
  </tr>
  <tr>
    <% @daily_tasks.each do |dt| %>
      <td><%= dt.title %></td>
      <td><%= dt.description %></td>
      <td><%= dt.complete %></td>
      <td><%= dt.updated_at %></td>
    </tr>
<% end %>
</table>

<%= link_to "Back to Daily Task list", current_day_lists_path, class: "btn btn-primary" %>

app/views/layouts/_header.html.erb
<div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <nav class="navbar navbar-inverse">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Daily Task Manager!", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">


          </ul>

          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li><%= link_to "Daily Tasks List", current_day_lists_path %></li>
              <li><%= link_to "All Tasks", tasks_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>

          </ul>
        </div><!-- /.navbar-collapse -->
        </nav>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SitDailyTasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/_task_table.html.erb
<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Completed</th>
  </tr>
  <% task.each do |dt| %>
    <tr>
      <td><%= dt.title %></td>
      <td><%= dt.description %></td>
      <% if dt.complete == false %>
        <td><%= link_to "Complete Task", done_task_path(dt, done_task: dt.id), class: "btn btn-success" %></td>
      <% else %>
        <td><%= link_to "Already Done", "#", class: "btn btn-success disabled" %>
        <%= link_to "Reset", reset_task_task_path(dt, reset_task: dt.id), class: "btn btn-warning btn-xs" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/static_pages/home.html.erb
<h2>
  Tasks for <%= @current_day_list.title %><br>
  <small>
    Completed Tasks: <%= @complete_task_count %>
    Incomplete Tasks: <%= @incomplete_task_count %>
  </small>
</h2>
<% if @incomplete_task_count == 0 %>
  <div class="col-md-4 col-md-offset-4">
    <p class="text-center">
      <%= image_tag("brentdance.gif")%>
    </p>
    <p class="text-center">
      All Tasks Done!
    </p>
  </div>
<% end %>

<div class="row"></div>

  <h3>Daily Tasks</h3>
  <%= render partial: "task_table", locals: {task: @daily_tasks} %>

</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div class="alert alert-danger">
    <strong>Errors</strong>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <p>
    Set date if this is a one-off task for a certain date.
  </p>
  <div class="form-group">
    <%= f.label :date_schedule %>
    <%= f.date_field :date_schedule, value: (Date.yesterday unless !@task.new_record?), class: "form-control" %>
  </div>
  <p>
    Select repeats and applicable days is a task repeats each week on a certain day.
  </p>
  <div class="form-group">
    <%= f.label :repeats %>
    <%= f.check_box :repeats, class: "form-control" %>
  </div>
<table class="table">
  <tr>
    <th><%= f.label :monday %></th>
    <th><%= f.label :tuesday %></th>
    <th><%= f.label :wednesday %></th>
    <th><%= f.label :thursday %></th>
    <th><%= f.label :friday %></th>
    <th><%= f.label :saturday %></th>
    <th><%= f.label :sunday %></th>
  </tr>
  <tr>
    <td><%= f.check_box :monday %></td>
    <td><%= f.check_box :tuesday %></td>
    <td><%= f.check_box :wednesday %></td>
    <td><%= f.check_box :thursday %></td>
    <td><%= f.check_box :friday %></td>
    <td><%= f.check_box :saturday %></td>
    <td><%= f.check_box :sunday %></td>
  </tr>
</table>
<div class="form-actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render 'tasks/form' %>
  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Back to Tasks", tasks_path, class: "btn btn-default" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="bg-info text-center top-info">
  <p>
    <h4>All Tasks</h4><br>
    You can create a new task and associate it with a single date, or create a recurring task that will appear each week on a specified day.
  </p>
</div><table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @tasks.each do |t| %>
    <tr>
      <td><%= t.title %></td>
      <td><%= t.description %></td>
      <td><%= link_to "Show", task_path(t), class: "btn btn-default" %></td>
      <td><%= link_to "Edit", edit_task_path(t), class: "btn btn-default" %></td>
      <td><%= link_to "Delete", t, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </tr>
  <% end %>
</table>

<%= link_to "New Task", new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render 'tasks/form' %>
  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Back to Tasks", tasks_path, class: "btn btn-default" %>
  </div>
</div>

app/views/tasks/show.html.erb
<ul class="list-unstyled">
  <li><strong>Title:</strong> <%= @task.title %></li>
  <li><strong>Description:</strong> <%= @task.description %></li>
  <li><strong>Date Scheduled:</strong> <%= @task.date_schedule.strftime("%A %d %B, %Y") %></li>
  <li><strong>Repeats:</strong> <%= @task.repeats %></li>
</ul>
<strong>Days Repeating</strong>
<table class="table">
  <tr>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
    <th>Sunday</th>
  </tr>
  <tr>
    <td><%= @task.monday %></td>
    <td><%= @task.tuesday %></td>
    <td><%= @task.wednesday %></td>
    <td><%= @task.thursday %></td>
    <td><%= @task.friday %></td>
    <td><%= @task.saturday %></td>
    <td><%= @task.sunday %></td>
  </tr>
</table>

<%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-default" %>

<%= link_to "Back to Tasks", tasks_path, class: "btn btn-default" %>